# Generated by Django 3.2 on 2024-12-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241224_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('END_USER', 'End user')], max_length=50, verbose_name='user type'),
        ),
    ]
