# Generated by Django 3.2 on 2024-12-24 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(max_length=7)),
                ('monthly_income', models.IntegerField(max_length=7)),
                ('status', models.CharField(choices=[('APPROVED', 'approved'), ('PENDING', 'pending'), ('DECLINED', 'declined')], default='PENDING', max_length=50, verbose_name='user type')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ('amount',),
            },
        ),
    ]
