# Generated by Django 3.2 on 2024-12-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('PENDING', 'pending'), ('DECLINED', 'declined')], default='PENDING', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='updated at'),
        ),
    ]
